# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(default='0', max_length=100, verbose_name='age'),
        ),
    ]
