# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20181008_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='0', max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(default='0', max_length=100, verbose_name='somethiing'),
        ),
    ]
