# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20181008_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='cost',
            field=models.CharField(default='0', max_length=100, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='person',
            name='product',
            field=models.CharField(default='0', max_length=100, verbose_name='product Name'),
        ),
    ]
